
```{r message=FALSE}
library("readr")
library("ggplot2")
library("dplyr")
```

```{r}
values     <- read_csv("http://berkeley.carlboettiger.info/espm-88b/fish/data/values.csv")
assessment <- read_csv("http://berkeley.carlboettiger.info/espm-88b/fish/data/assessment.csv")
stock      <- read_csv("http://berkeley.carlboettiger.info/espm-88b/fish/data/stock.csv")
units      <- read_csv("http://berkeley.carlboettiger.info/espm-88b/fish/data/units.csv")
area       <- read_csv("http://berkeley.carlboettiger.info/espm-88b/fish/data/area.csv")
lmestock   <- read_csv("http://berkeley.carlboettiger.info/espm-88b/fish/data/lmestock.csv")
lmerefs    <- read_csv("http://berkeley.carlboettiger.info/espm-88b/fish/data/lmerefs.csv")
```


```{r}
tbl <-
  values %>%
  left_join(assessment) %>%
  left_join(stock) %>%
  left_join(units) %>%
  left_join(area) %>%
  left_join(lmestock) %>%
  left_join(lmerefs) %>%
  select(scientificname, commonname, tsyear, r, ssb, total, catch_landings, r_unit, ssb_unit, total_unit, catch_landings_unit, country, lme_number, lme_name)
```

Sum over all assessments of a given species in a given year that are harvested

```{r}
tbl %>%
  filter(catch_landings_unit == 'MT') %>%
  filter(tsyear >= 1950) %>%
  filter(tsyear <= 2006) %>%
  group_by(tsyear) %>%
  summarise(catch_landings = sum(catch_landings, na.rm=TRUE)) %>%
  ggplot() + geom_line(aes(tsyear, catch_landings))
```


Newfoundland Atlantic Cod Catch

```{r}
tbl %>%
  group_by(commonname, lme_name, tsyear) %>%
  summarise(catch_landings = sum(catch_landings, na.rm = TRUE)) %>%
  filter(lme_name == "Newfoundland-Labrador Shelf") %>%
  filter(commonname == "Atlantic cod") %>%
  ggplot(aes(tsyear, catch_landings)) + geom_line()
```

Using only those with consistent units for 'total stock' and 'catch', compute an escapement column

```{r}
tbl %>%
  filter(total_unit == catch_landings_unit) %>%
#  filter(r_unit == ssb_unit) %>%
  mutate(escapement = total - catch_landings) %>%
  group_by(commonname, lme_name, tsyear) %>%
  summarise(escapement = sum(escapement, na.rm = TRUE), 
            total = sum(total, na.rm = TRUE),
            r = sum(r, na.rm = TRUE),
            ssb = sum(ssb, na.rm = TRUE)) ->
  grouped
```

Newfoundland Atlantic Cod escapement

```{r}
grouped  %>%
  filter(lme_name == "Newfoundland-Labrador Shelf") %>%
  filter(commonname == "Atlantic cod") %>%
  ggplot(aes(total, escapement)) + geom_line()
```



```{r}
grouped  %>%
  filter(lme_name == "Newfoundland-Labrador Shelf") %>%
  filter(commonname == "Atlantic cod") %>%
  ggplot(aes(escapement, total)) + geom_line()
```



Identify all LMEs harvested by USA boats

```{r}
stock_country_lme <-
  stock %>%
  left_join(area) %>%
  left_join(lmestock) %>%
  left_join(lmerefs) %>%
  select(scientificname, commonname, country, lme_name, areatype)

usa_lmes <-
  stock_country_lme %>%
  filter(country == "USA") %>%
  select(lme_name) %>%
  unique() %>% 
  na.exclude() %>%
  first() 
```

```{r}
for(lme in usa_lmes){
tbl %>%
  group_by(commonname, lme_name, tsyear) %>%
  summarise(escapement = sum(escapement, na.rm = TRUE), total = sum(total, na.rm = TRUE)) %>%
  filter(lme_name == lme) -> df
  p <- ggplot(df, aes(total, escapement, col = commonname)) + geom_line() + facet_wrap(~lme_name)
  print(p)
}
```

